# coding: utf-8

"""
    Telstra Programmable Network API

    Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.  # noqa: E501

    OpenAPI spec version: 2.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TelstraTPN
from TelstraTPN.api.vports_api import VportsApi  # noqa: E501
from TelstraTPN.rest import ApiException


class TestVportsApi(unittest.TestCase):
    """VportsApi unit test stubs"""

    def setUp(self):
        self.api = TelstraTPN.api.vports_api.VportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_inventory_regularvport_post(self):
        """Test case for inventory_regularvport_post

        Create VPort for physical endpoint  # noqa: E501
        """
        pass

    def test_inventory_vnf_vport_post(self):
        """Test case for inventory_vnf_vport_post

        Create VNF VPort  # noqa: E501
        """
        pass

    def test_inventory_vport_by_vportuuid_get(self):
        """Test case for inventory_vport_by_vportuuid_get

        Get information about the specified VPort  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
