# coding: utf-8

"""
    Telstra Programmable Network API

    Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.  # noqa: E501

    OpenAPI spec version: 2.4.2
    Contact: pnapi-support@team.telstra.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import TelstraTPN
from TelstraTPN.models.inline_response2001_endpointlist import InlineResponse2001Endpointlist  # noqa: E501
from TelstraTPN.rest import ApiException


class TestInlineResponse2001Endpointlist(unittest.TestCase):
    """InlineResponse2001Endpointlist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001Endpointlist(self):
        """Test InlineResponse2001Endpointlist"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TelstraTPN.models.inline_response2001_endpointlist.InlineResponse2001Endpointlist()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
