# coding: utf-8

"""
    Telstra Programmable Network API

    Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.  # noqa: E501

    OpenAPI spec version: 2.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import TelstraTPN
from TelstraTPN.api.endpoints_api import EndpointsApi  # noqa: E501
from TelstraTPN.rest import ApiException


class TestEndpointsApi(unittest.TestCase):
    """EndpointsApi unit test stubs"""

    def setUp(self):
        self.api = TelstraTPN.api.endpoints_api.EndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_eis100_endpoints_assign_topology_tag_by_endpointuuid_post(self):
        """Test case for eis100_endpoints_assign_topology_tag_by_endpointuuid_post

        Assign a Topology Tag to an Endpoint  # noqa: E501
        """
        pass

    def test_inventory_endpoint_by_endpointuuid_get(self):
        """Test case for inventory_endpoint_by_endpointuuid_get

        Get information about the specified endpoint  # noqa: E501
        """
        pass

    def test_inventory_endpoints_customeruuid_by_customeruuid_get(self):
        """Test case for inventory_endpoints_customeruuid_by_customeruuid_get

        Get list of endpoints for a customer  # noqa: E501
        """
        pass

    def test_inventory_regularendpoint_post(self):
        """Test case for inventory_regularendpoint_post

        Create Physical (Port) Endpoint  # noqa: E501
        """
        pass

    def test_inventory_vnfendpoint_post(self):
        """Test case for inventory_vnfendpoint_post

        Create VNF Endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
