# coding: utf-8

"""
    Telstra Programmable Network API

    Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

    OpenAPI spec version: 2.1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import TelstraTPN
from TelstraTPN.rest import ApiException
from TelstraTPN.models.model_100_inventory_links_contract_response36 import Model100InventoryLinksContractResponse36


class TestModel100InventoryLinksContractResponse36(unittest.TestCase):
    """ Model100InventoryLinksContractResponse36 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel100InventoryLinksContractResponse36(self):
        """
        Test Model100InventoryLinksContractResponse36
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = TelstraTPN.models.model_100_inventory_links_contract_response36.Model100InventoryLinksContractResponse36()
        pass


if __name__ == '__main__':
    unittest.main()
