# coding: utf-8

"""
    Telstra Programmable Network API

    Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.  # noqa: E501

    OpenAPI spec version: 2.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from TelstraTPN.api_client import ApiClient


class VportsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def inventory_regularvport_post(self, **kwargs):  # noqa: E501
        """inventoryregularvportpost  # noqa: E501

        Create VPort representing a VLAN on a Physical Ethernet Port  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.inventory_regularvport_post(async=True)
        >>> result = thread.get()

        :param async bool
        :param Body53 body: 
        :return: InventoryregularvportpostResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.inventory_regularvport_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.inventory_regularvport_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def inventory_regularvport_post_with_http_info(self, **kwargs):  # noqa: E501
        """inventoryregularvportpost  # noqa: E501

        Create VPort representing a VLAN on a Physical Ethernet Port  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.inventory_regularvport_post_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param Body53 body: 
        :return: InventoryregularvportpostResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method inventory_regularvport_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['auth']  # noqa: E501

        return self.api_client.call_api(
            '/1.0.0/inventory/regularvport', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InventoryregularvportpostResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def inventory_vnf_vport_post(self, **kwargs):  # noqa: E501
        """inventoryvnfvportpost  # noqa: E501

        Create VNF VPort  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.inventory_vnf_vport_post(async=True)
        >>> result = thread.get()

        :param async bool
        :param Body56 body: 
        :return: InventoryvnfvportpostResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.inventory_vnf_vport_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.inventory_vnf_vport_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def inventory_vnf_vport_post_with_http_info(self, **kwargs):  # noqa: E501
        """inventoryvnfvportpost  # noqa: E501

        Create VNF VPort  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.inventory_vnf_vport_post_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param Body56 body: 
        :return: InventoryvnfvportpostResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method inventory_vnf_vport_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['auth']  # noqa: E501

        return self.api_client.call_api(
            '/1.0.0/inventory/vnf/vport', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InventoryvnfvportpostResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def inventory_vport_by_vportuuid_get(self, vportuuid, **kwargs):  # noqa: E501
        """inventoryvportvportuuidget  # noqa: E501

        Get information about the specified VPort  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.inventory_vport_by_vportuuid_get(vportuuid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str vportuuid: Unique identifier representing a specific virtual port (required)
        :return: EndpointPort
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.inventory_vport_by_vportuuid_get_with_http_info(vportuuid, **kwargs)  # noqa: E501
        else:
            (data) = self.inventory_vport_by_vportuuid_get_with_http_info(vportuuid, **kwargs)  # noqa: E501
            return data

    def inventory_vport_by_vportuuid_get_with_http_info(self, vportuuid, **kwargs):  # noqa: E501
        """inventoryvportvportuuidget  # noqa: E501

        Get information about the specified VPort  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.inventory_vport_by_vportuuid_get_with_http_info(vportuuid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str vportuuid: Unique identifier representing a specific virtual port (required)
        :return: EndpointPort
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['vportuuid']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method inventory_vport_by_vportuuid_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'vportuuid' is set
        if ('vportuuid' not in params or
                params['vportuuid'] is None):
            raise ValueError("Missing the required parameter `vportuuid` when calling `inventory_vport_by_vportuuid_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'vportuuid' in params:
            path_params['vportuuid'] = params['vportuuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['auth']  # noqa: E501

        return self.api_client.call_api(
            '/1.0.0/inventory/vport/{vportuuid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EndpointPort',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
